=== abnormy/EnExt/.BuildServer/config/main-config.dtd
<?xml version='1.0' encoding='ISO-8859-1' ?>

<!ENTITY % common SYSTEM "common.dtd">
%common;

<!--
     This is a DTD for Jetbrains BuildServer configuration file,
     placed at $HOME/.BuildServer/config/main-config.xml
-->

<!-- Server root - set of Build Types and User Groups -->
<!ELEMENT server (version|db-compact|backup|auth-type|artifacts|report-tab|comment-transformation|permissions|build-metrics|build-settings)*>
<!ATTLIST server
    rootURL CDATA #IMPLIED
>

<!ELEMENT version EMPTY>
<!ATTLIST version
    number CDATA #REQUIRED
>

<!ELEMENT db-compact (options|scheduler|policy)*>

<!ELEMENT scheduler (#PCDATA)>
<!ATTLIST scheduler
    hour CDATA #IMPLIED
    minute CDATA #IMPLIED
    day-of-week (monday|tuesday|wednesday|thursday|friday|saturday|sunday) #IMPLIED
>

<!ELEMENT backup (backup-dir?)>

<!ELEMENT backup-dir EMPTY>
<!ATTLIST backup-dir
    path CDATA #REQUIRED
>

<!ELEMENT auth-type (login-module?, login-description?, guest-login?, free-registration?)>
<!ELEMENT login-module EMPTY>
<!ATTLIST login-module
    class CDATA #REQUIRED
>
<!ELEMENT login-description (#PCDATA)>

<!ELEMENT guest-login EMPTY>
<!ATTLIST guest-login
    allowed (true|false|yes|no) #REQUIRED
    guest-username CDATA #IMPLIED
>

<!ELEMENT free-registration EMPTY>
<!ATTLIST free-registration
    allowed (true|false|yes|no) #REQUIRED
>

<!ELEMENT report-tab EMPTY>
<!ATTLIST report-tab
    title CDATA #REQUIRED
    startPage CDATA #IMPLIED
>

<!ELEMENT comment-transformation (transformation-pattern)*>
<!ELEMENT transformation-pattern EMPTY>
<!ATTLIST transformation-pattern
    search CDATA #REQUIRED
    replace CDATA #REQUIRED
    description CDATA #IMPLIED
>

<!ELEMENT artifacts EMPTY>
<!ATTLIST artifacts
    maxArtifactSize CDATA #IMPLIED
>

<!ELEMENT build-settings EMPTY>
<!ATTLIST build-settings
    executionTimeout CDATA #IMPLIED
>

<!ELEMENT permissions EMPTY>
<!ATTLIST permissions
    perProjectPermissions (true|false|yes|no) #REQUIRED
>

<!ELEMENT build-metrics (statisticValue)*>
<!ELEMENT statisticValue EMPTY>
<!ATTLIST statisticValue
    key CDATA #REQUIRED
    description CDATA #REQUIRED
>

=== abnormy/EnExt/.BuildServer/config/main-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE server SYSTEM "main-config.dtd">

<server>
  <version number="514" />
  <db-compact>
    <scheduler hour="3" minute="0" />
  </db-compact>
  <auth-type>
    <free-registration allowed="true" />
  </auth-type>
  <artifacts maxArtifactSize="300000000" />
  <comment-transformation>
    <transformation-pattern search="((https?://|ftp://|file://|mailto:)[\w`~@#$%^&amp;*-=|\/{}()\[\];:&quot;'&lt;&gt;?\.]+(?&lt;=[^\.,;&quot;'`\)\]}]))" replace="&lt;a target=&quot;_blank&quot; title=&quot;Click to open this link in a new window&quot; href=&quot;$1&quot;&gt;$1&lt;/a&gt;" description="Links transformation (default)" />
    <transformation-pattern search="(&#xD;?&#xA;|&#xD;)" replace="&lt;br&gt;" description="Line feed transformation (default)" />
  </comment-transformation>
  <report-tab title="Code Coverage" startPage="coverage.zip!index.html" />
  <report-tab title="JavaDoc" startPage="javadoc.zip!index.html" />
</server>
